Merge w/ grouped:filter,comp.info,colored curses,histogram
Puentes-Digitales/TrAC pull request #2
Opened 2021-02-09 19:51 UTC by moyarzun94

2021-02-17 02:53 UTC, PabloSzx commented on api/dataloaders/program.ts
> +        const data = await CourseGroupedStatsTable().where({
Esta solicitud se puede optimizar considerablemente, ya que si se piden 10 programas distintos, se están haciendo 10 llamadas separadas a la base de datos, cuando se puede pedir toda la información en una sola llamada y devolverla, esa es el objetivo principal de los dataloaders

2021-02-17 03:20 UTC, PabloSzx requested changes
dejé comentarios de las dudas que tengo, pero también me gustaría saber si pretenden dejar los arreglos a la api pendientes para este PR o para el siguiente

2021-02-17 03:20 UTC, PabloSzx commented on client/src/components/dashboard/Dashboard.tsx
> +          })[0] ?? [],
Necesito saber que es que se busca con todo esto, porque además de estar muy mal optimizado, los últimos map la verdad es que me dejan completamente confundido

2021-02-17 03:20 UTC, PabloSzx commented on client/src/components/dashboard/GroupedComplementaryInfo.tsx
> +                    <Text width="290px" pl={5} pb={0} mb={0} fontFamily="Lato">
por qué están definiendo el fontFamily="Lato" en todos los textos de esta sección? si definiendolo en el div contenedor debe bastar?

2021-02-19 15:02 UTC, FabianMorag commented on api/dataloaders/program.ts
> +        const data = await CourseGroupedStatsTable().where({
Este dataloader se llama desde el resolver program.ts, este resolver siempre recibe un pograma cada vez que se realiza una consulta, entonces a pesar de que el dataloader recibe un arreglo de programas, la consulta siempre se realiza con un arreglo de largo 1.  Por ejemplo, la query se hace cuando un director selecciona una carrera en la vista agrupada se realiza la consulta con un solo program_id, o cuando se busca un estudiante también se realiza la consulta con un solo program_id. Definimos el dataloader asi guiandonos por las estructura que ya habia en los anteriores dataloader.

2021-02-19 15:02 UTC, FabianMorag commented on client/src/components/dashboard/Dashboard.tsx
> +          })[0] ?? [],
Corregido.

2021-02-19 15:03 UTC, FabianMorag commented on client/src/components/dashboard/GroupedComplementaryInfo.tsx
> +                    <Text width="290px" pl={5} pb={0} mb={0} fontFamily="Lato">
Corregido.

2021-02-19 23:44 UTC, PabloSzx commented on client/src/components/dashboard/Dashboard.tsx
> +          })[0] ?? [],
no hay ningun commit agregado

2021-02-20 02:23 UTC, PabloSzx commented
Acabo de encontrar un error grave, si un dataloader recibe objetos como parametros se debe definir cacheKeyFn que retorne un valor primitivo, normalmente string, todos los dataloaders tienen que hacerlo, este si lo hace por ejemplo: https://github.com/Puentes-Digitales/TrAC/blob/3391fdf40ac5311a3ee6c236c6d4ac0f55001dba/api/dataloaders/program.ts#L73

y este no lo hace: https://github.com/Puentes-Digitales/TrAC/blob/3391fdf40ac5311a3ee6c236c6d4ac0f55001dba/api/dataloaders/program.ts#L231

2021-02-24 13:11 UTC, FabianMorag commented
> Acabo de encontrar un error grave, si un dataloader recibe objetos como parametros se debe definir cacheKeyFn que retorne un valor primitivo, normalmente string, todos los dataloaders tienen que hacerlo, este si lo hace por ejemplo:
> 
> https://github.com/Puentes-Digitales/TrAC/blob/3391fdf40ac5311a3ee6c236c6d4ac0f55001dba/api/dataloaders/program.ts#L73
> 
> y este no lo hace:
> 
> https://github.com/Puentes-Digitales/TrAC/blob/3391fdf40ac5311a3ee6c236c6d4ac0f55001dba/api/dataloaders/program.ts#L231
> 
> y aquí la documentación de "dataloader" https://github.com/graphql/dataloader#new-dataloaderbatchloadfn--options

Esto debería estar corregido ya

2021-02-24 14:08 UTC, FabianMorag commented
> dejé comentarios de las dudas que tengo, pero también me gustaría saber si pretenden dejar los arreglos a la api pendientes para este PR o para el siguiente

Estos errores están solucionados asi que irán en alguno de PR siguientes

2021-02-26 18:10 UTC, FabianMorag commented
> dejé comentarios de las dudas que tengo, pero también me gustaría saber si pretenden dejar los arreglos a la api pendientes para este PR o para el siguiente

Para el siguiente

2021-02-28 23:08 UTC, PabloSzx approved these changes

2021-03-01 12:51 UTC, merged